name = "nike"
compatibility_date = "2025-06-13"
route = { pattern = "nike.massimilianoporzio.com", custom_domain= true }

[assets]
  directory = "./dist"
  not_found_handling = "single-page-application"
